### ISSUE TITLE
no logout.html file in templates folder (tutorial3)

### ISSUE THREAD

**Issue by ssenthilnathan3** [techwithtim/Flask-Blog-Tutorial#3]
In turtorial3 file, here is no logout.html file in the templates file but there is a reference "href="/logout" in base.html in line 30

I don't know if I am right or completely wrong about this.

If I am wrong, sorry for your waste of time

**Comment by transcental** [comment]
There doesn't need to be a `logout.html` file. The link will probably log the user out and redirect to the main page.

**Comment by ssenthilnathan3** [comment]
Thank you, I noticed it now.
