### ISSUE TITLE
Issue deleting posts

### ISSUE THREAD

**Issue by jason4835** [techwithtim/Flask-Blog-Tutorial#4]
After testing the finished product I have noticed that when you make more than one post the website says that you do not have permission to delete the second post

**Comment by evilbetty** [comment]
In views.py the following line seems to be wrong:
`elif current_user.id != post.id:`
I believe it should be:
`elif current_user.id != post.author:`

Now the current user's id is being checked against the post's id, which worked in the video because the user and post id were both 2.
